# Generated by Django 3.1.6 on 2021-02-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
