# Generated by Django 3.1.6 on 2021-02-01 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='name',
        ),
    ]
